### ISSUE TITLE
`ld: framework not found FBLPromises`

### ISSUE THREAD

**Issue by imWildCat** [akaffenberger/firebase-ios-sdk-xcframeworks#21]
Hello, I'm seeing this error:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/2396817/160402725-193ef8fc-78d4-449b-87a7-1224e235993a.png">

ld: framework not found FBLPromises
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Even if I got <https://github.com/google/promises/blob/master/g3doc/index.md#add-dependency> installed:
<img width="173" alt="image" src="https://user-images.githubusercontent.com/2396817/160402685-b57a5c3e-3222-44ea-84dd-bf67e8d04bd8.png">

I'm still seeing the same error:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/2396817/160402725-193ef8fc-78d4-449b-87a7-1224e235993a.png">

**Comment by imWildCat** [comment]
Oh my bad! It is due to legacy CocoaPods flags.

**Comment by akaffenberger** [comment]
Thanks @imWildCat! I was also able to reproduce this by trying to use the package without including the "-ObjC" linker flag in project settings.

Fixed here (includes the linker flag in Package.swift):  
https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/commit/0510538b1b3071e8f8bd4a529545243c07ee4110
