### ISSUE TITLE
No such module 'xxx' errors.

### ISSUE THREAD

**Issue by kamimi01** [akaffenberger/firebase-ios-sdk-xcframeworks#41]
Hi, @akaffenberger 
Thank you for creating a great library!

I'm new to Swift Package. I'm stuck on the following problems. Would you mind telling me how to fix them?

## Description

I've got `No such module 'xxx'` errors.

![image](https://user-images.githubusercontent.com/47489629/187052871-77e837f3-b6aa-4c68-8e34-e03cc3a3297d.png)

I think the cause is my project can't get source files from firebase-sdk-ios because there is still a dummy file in each product in the following screenshot. I know [`package.sh`](https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/blob/master/.scripts/package.sh) will get those files, but I don't understand how I should run that script. (Copy the script into my project and run it?)

![image](https://user-images.githubusercontent.com/47489629/187052930-8170a8b2-be49-484b-b257-d19f5f97db65.png)

## What I did

- Add the package

![image](https://user-images.githubusercontent.com/47489629/187052986-9293dc2d-f96c-420b-9014-dc3356525091.png)

Here is my package.swfit.

```swift
// swift-tools-version:5.3
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "FirebaseSDK",
    platforms: [.iOS(.v11)],
    products: [
        .library(name: "FirebaseSDK", targets: ["FirebaseSDK"])
    ],
    dependencies: [
        .package(
            name: "Firebase",
            url: "https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks.git",
            .exact("9.5.0")
        ),
    ],
    targets: [
        .target(
            name: "FirebaseSDK",
            dependencies: [  // products that I want to use
                .product(name: "FirebaseAnalytics", package: "Firebase"),
                .product(name: "FirebaseAuth", package: "Firebase"),
                .product(name: "FirebaseFirestore", package: "Firebase"),
                .product(name: "FirebaseCrashlytics", package: "Firebase"),
                .product(name: "GoogleSignIn", package: "Firebase")
            ]
        )
    ]
)
```

- Add -ObjC to Build Settings -> Other Linker Flags

![image](https://user-images.githubusercontent.com/47489629/187053036-506c6d04-4a4c-4926-9296-5cd1f67a15f7.png)

- Copy the script into a Run Script Phase:

![image](https://user-images.githubusercontent.com/47489629/187053033-1074c4cd-fe91-45cd-9a73-cc6e233f51a7.png)

**Comment by akaffenberger** [comment]
Hi @kamimi01! Based on the screenshots, it looks like you're trying to use this package with your DivingTips XCode project. XCode has SPM built-in, so you do not need to create a Package.swift file. 

Click on your DivingTips project, the root folder:
<img width="357" alt="Screen Shot 2022-10-05 at 8 06 43 PM" src="https://user-images.githubusercontent.com/61200282/194185635-6268b895-1fef-4401-be9a-055453719917.png">

Then you should see a list of all your targets underneath "TARGETS", and your project underneath "PROJECT". Click on the project. Then click on the "Package Dependencies" tab and add this package with the '+' sign at the bottom. 
<img width="1127" alt="Screen Shot 2022-10-05 at 8 26 19 PM" src="https://user-images.githubusercontent.com/61200282/194187240-2663d1e1-ac67-478c-88d5-f25c986e6469.png">

Make sure you select all the libraries you want to use. In your case select "GoogleSignIn".
<img width="654" alt="Screen Shot 2022-10-05 at 8 26 00 PM" src="https://user-images.githubusercontent.com/61200282/194187262-803c100a-e469-4d22-8cde-6f94c2c517bb.png">

You should be good to go from there.

If you need to further troubleshoot, you can also check which libraries are included if you go to Targets -> DivingTips -> General -> Frameworks, Libraries and Embedded Content. You want to see GoogleSignIn in the list, if it's not there you can add it via the '+' sign:
<img width="1374" alt="Screen Shot 2022-10-05 at 8 23 46 PM" src="https://user-images.githubusercontent.com/61200282/194186977-4456580a-8cd2-482a-9ec0-a63da16be553.png">

Also, to further clarify what this project is doing -- the `package.sh` script you mentioned is not meant to be used externally, it is a script this project uses internally (it pulls down the latest Firebase binaries, generates the Package.swift file for this repo, and then uploads the binaries to this repo). You don't need to worry about running that.

If you are still having issues or have any other questions don't hesitate to ask!
