### ISSUE TITLE
Sources can be removed from this repo, right?

### ISSUE THREAD

**Issue by lazar-otasevic-cif** [akaffenberger/firebase-ios-sdk-xcframeworks#44]
There are many source files that can be removed, correct?

**Comment by sisoje** [comment]
but run and upload-symbols binaries are needed

**Comment by akaffenberger** [comment]
@lazar-otasevic-cif Are you referring to the dummy files? Those are there because SPM will complain (compile error) if a target's resource folder is empty.

**Comment by sisoje** [comment]
ah all good
