### ISSUE TITLE
FirebaseFirestoreSwift is not included

### ISSUE THREAD

**Issue by jesus-mg-ios** [akaffenberger/firebase-ios-sdk-xcframeworks#50]
I cannot use FirebaseFirestoreSwift from this repo

**Comment by akaffenberger** [comment]
@jesus-mg-ios I'm not able to reproduce this issue in the [iOS Example](https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/tree/master/iOS%20Example) in this repo, which is [importing and using `FirebaseFirestoreSwift`](https://github.com/akaffenberger/firebase-ios-sdk-xcframeworks/blob/master/iOS%20Example/iOS%20Example/Views/FirestoreView.swift). 

When you say cannot use do you mean you cannot import the module? If that is the case, are you able to import other modules (ie `Firebase`, `FirebaseFirestore`, etc). Have you confirmed that FirebaseFirestore is included in your target's "Link Binary with Libraries" build phase?

**Comment by akaffenberger** [comment]
Closing for now due to inactivity, but happy to reopen if others are experiencing this as well.
